# Generated by Django 4.2.4 on 2023-09-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=255)),
                ('upload_date', models.DateField()),
                ('genre', models.CharField(max_length=50)),
                ('publish_year', models.PositiveIntegerField()),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
    ]
