# Generated by Django 4.2.4 on 2023-09-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='general_Book',
        ),
    ]
