# Generated by Django 4.2.4 on 2023-09-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_journals_novels_papers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='general_Book',
            new_name='GeneralBook',
        ),
        migrations.RenameModel(
            old_name='journals',
            new_name='Journal',
        ),
        migrations.RenameModel(
            old_name='novels',
            new_name='Novel',
        ),
        migrations.RenameModel(
            old_name='papers',
            new_name='Paper',
        ),
    ]
