# Generated by Django 4.2.4 on 2023-09-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_courses_fr1_fr2_frst1_frst2_sc1_sc2_thr1_thr2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fr1',
        ),
        migrations.DeleteModel(
            name='fr2',
        ),
        migrations.DeleteModel(
            name='frst1',
        ),
        migrations.DeleteModel(
            name='frst2',
        ),
        migrations.DeleteModel(
            name='sc1',
        ),
        migrations.DeleteModel(
            name='sc2',
        ),
        migrations.DeleteModel(
            name='thr1',
        ),
        migrations.DeleteModel(
            name='thr2',
        ),
    ]
