# Generated by Django 4.2.4 on 2023-09-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_delete_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='fr1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=100)),
                ('publish_year', models.IntegerField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=255)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='fr2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=100)),
                ('publish_year', models.IntegerField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=255)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='frst1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=100)),
                ('publish_year', models.IntegerField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=255)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='frst2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=100)),
                ('publish_year', models.IntegerField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=255)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='sc1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=100)),
                ('publish_year', models.IntegerField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=255)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='sc2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=100)),
                ('publish_year', models.IntegerField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=255)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thr1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=100)),
                ('publish_year', models.IntegerField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=255)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='thr2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
                ('book_author', models.CharField(max_length=100)),
                ('publish_year', models.IntegerField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=255)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
