# Generated by Django 4.2.4 on 2023-09-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_student_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_login',
        ),
    ]
