# Generated by Django 4.2.4 on 2023-09-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_student_id_student_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
